import type { Metadata } from "next";
import { Geist, Geist_Mono, League_Spartan } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "next-themes";
import { Toaster } from "sonner";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const leagSpartan = League_Spartan({subsets: ['latin'] ,weight: ['100','200','300','400','500','600','700','800','900']})

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Medora",
  description: "Generated by create next app",
  authors: [{name: "Medora"}]
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${leagSpartan.className} ${geistMono.variable} antialiased`}
      >
       <ThemeProvider
        attribute="class"
        defaultTheme="system"
        enableSystem
        disableTransitionOnChange
       >
        <Toaster/>
       <main className="w-full min-h-screen">
        <div className="">
            {children}
        </div>
       </main>
       </ThemeProvider>
      </body>
    </html>
  );
}
