import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter, League_Spartan, Urbanist } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "next-themes";
import { Toaster } from "sonner";
import { AuthProvider } from "@/context/auth/authContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const inter = Inter({
    variable: "--font-sans",
    subsets: ["latin"],
    weight: ['100','200','300','400','500','600','700','800','900']
});

const urbanist = Urbanist({
    variable: "--font-urbanist",
    subsets: ["latin"],
    weight: ['100','200','300','400','500','600','700','800','900']
});

const leagSpartan = League_Spartan({subsets: ['latin'] ,weight: ['100','200','300','400','500','600','700','800','900']})

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Medora",
  description: "Generated by create next app",
  authors: [{name: "Medora"}]
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${urbanist.className}  ${geistMono.variable} antialiased`}
      >
       <ThemeProvider
        attribute="class"
        defaultTheme="light"
        enableSystem
        disableTransitionOnChange
       >
        <Toaster/>
       <main className="w-full min-h-screen">
        <div className="">
            <AuthProvider>
              {children}
            </AuthProvider>
        </div>
       </main>
       </ThemeProvider>
      </body>
    </html>
  );
}
