// lib/pdf/pdf-utils.ts
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

// Extend jsPDF type
declare module 'jspdf' {
  interface jsPDF {
    autoTable: (options: any) => jsPDF;
    lastAutoTable: { finalY: number };
  }
}

export interface PDFColors {
  primary: [number, number, number];
  secondary: [number, number, number];
  accent: [number, number, number];
  success: [number, number, number];
  warning: [number, number, number];
  error: [number, number, number];
  background: [number, number, number];
  text: {
    primary: [number, number, number];
    secondary: [number, number, number];
    light: [number, number, number];
  };
}

export const MEDORA_COLORS: PDFColors = {
  primary: [0, 102, 204], // Medora Blue
  secondary: [108, 117, 125], // Gray
  accent: [111, 66, 193], // Purple
  success: [40, 167, 69], // Green
  warning: [255, 193, 7], // Yellow
  error: [220, 53, 69], // Red
  background: [245, 247, 250], // Light Gray
  text: {
    primary: [33, 37, 41],
    secondary: [73, 80, 87],
    light: [108, 117, 125]
  }
};

export const addMedoraHeader = (
  pdf: jsPDF, 
  title: string, 
  subtitle?: string,
  patientName?: string
) => {
  const pageWidth = pdf.internal.pageSize.getWidth();
  const margin = 20;

  // Add Medora Logo
  pdf.setFillColor(MEDORA_COLORS.primary[0], MEDORA_COLORS.primary[1], MEDORA_COLORS.primary[2]);
  pdf.rect(margin, margin, 8, 8, 'F');
  
  pdf.setFontSize(20);
  pdf.setTextColor(MEDORA_COLORS.primary[0], MEDORA_COLORS.primary[1], MEDORA_COLORS.primary[2]);
  pdf.setFont('helvetica', 'bold');
  pdf.text('MEDORA', margin + 12, margin + 7);
  
  pdf.setFontSize(10);
  pdf.setTextColor(MEDORA_COLORS.text.light[0], MEDORA_COLORS.text.light[1], MEDORA_COLORS.text.light[2]);
  pdf.setFont('helvetica', 'normal');
  pdf.text('Health Assistant', margin + 12, margin + 12);

  // Decorative line
  pdf.setDrawColor(MEDORA_COLORS.primary[0], MEDORA_COLORS.primary[1], MEDORA_COLORS.primary[2]);
  pdf.setLineWidth(0.5);
  pdf.line(margin, margin + 15, pageWidth - margin, margin + 15);

  // Title
  pdf.setFontSize(24);
  pdf.setTextColor(MEDORA_COLORS.text.primary[0], MEDORA_COLORS.text.primary[1], MEDORA_COLORS.text.primary[2]);
  pdf.setFont('helvetica', 'bold');
  pdf.text(title, margin, margin + 30);

  // Date and Report ID
  pdf.setFontSize(9);
  pdf.setTextColor(MEDORA_COLORS.text.light[0], MEDORA_COLORS.text.light[1], MEDORA_COLORS.text.light[2]);
  pdf.setFont('helvetica', 'normal');
  const today = new Date();
  pdf.text(`Report Date: ${today.toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}`, margin, margin + 37);
  pdf.text(`Report ID: ${title.replace(/\s+/g, '-').toUpperCase()}-${today.getTime().toString().slice(-8)}`, margin, margin + 42);
  
  if (patientName) {
    pdf.text(`Patient: ${patientName}`, pageWidth - margin - 70, margin + 37);
  }

  if (subtitle) {
    pdf.setFontSize(11);
    pdf.setTextColor(MEDORA_COLORS.text.secondary[0], MEDORA_COLORS.text.secondary[1], MEDORA_COLORS.text.secondary[2]);
    pdf.text(subtitle, margin, margin + 50);
    return margin + 55;
  }

  return margin + 45;
};

export const addSectionHeader = (
  pdf: jsPDF,
  y: number,
  title: string,
  color: [number, number, number] = MEDORA_COLORS.primary
) => {
  const margin = 20;
  const pageWidth = pdf.internal.pageSize.getWidth();
  const contentWidth = pageWidth - (margin * 2);

  pdf.setFillColor(color[0], color[1], color[2]);
  pdf.roundedRect(margin, y, contentWidth, 8, 2, 2, 'F');
  
  pdf.setFontSize(11);
  pdf.setTextColor(255, 255, 255);
  pdf.setFont('helvetica', 'bold');
  pdf.text(title.toUpperCase(), margin + 5, y + 6);
  
  return y + 12;
};

export const addFooter = (pdf: jsPDF, pageNumber?: number) => {
  const pageWidth = pdf.internal.pageSize.getWidth();
  const margin = 20;
  const footerY = pdf.internal.pageSize.getHeight() - 20;

  // Line separator
  pdf.setDrawColor(200, 200, 200);
  pdf.setLineWidth(0.3);
  pdf.line(margin, footerY - 5, pageWidth - margin, footerY - 5);
  
  pdf.setFontSize(8);
  pdf.setTextColor(MEDORA_COLORS.text.light[0], MEDORA_COLORS.text.light[1], MEDORA_COLORS.text.light[2]);
  pdf.text('This document is generated by Medora AI Assistant.', margin, footerY);
  pdf.text('Contains confidential medical information.', margin, footerY + 4);
  
  if (pageNumber) {
    pdf.text(`Page ${pageNumber}`, pageWidth - margin - 15, footerY);
  }
};